if(tool STREQUAL "valgrind")
  set(command "${valgrind}" --quiet --error-exitcode=97 "${probe}" "${mode}")
elseif(tool STREQUAL "msan")
  # The expected diagnostic does not require symbolization or remote debug-info downloads.
  set(command "${CMAKE_COMMAND}" -E env MSAN_OPTIONS=exit_code=97:halt_on_error=1:symbolize=0 "${probe}" "${mode}")
else()
  message(FATAL_ERROR "Unknown initialization diagnostic tool: ${tool}")
endif()
execute_process(COMMAND ${command} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
if(mode STREQUAL "complete")
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Fully initialized storage failed (${result}):\n${output}\n${error}")
  endif()
else()
  if(NOT result EQUAL 97 OR NOT error MATCHES "[Uu]ninitiali[sz]ed|undefined")
    message(FATAL_ERROR "Expected an undefined-value diagnostic and exit 97, got ${result}:\n${output}\n${error}")
  endif()
endif()
