#[[
Detect and normalize the BLAS vendor from its target or package variables.

Output cache variables:
  - UNI20_DETECTED_BLAS_VENDOR
  - UNI20_DETECTED_BLAS_VENDOR_MACRO
  - UNI20_DETECTED_BLAS_LIBRARIES
]]

function(_uni20_map_blas_vendor_name input_value output_var)
  if(input_value STREQUAL "")
    set(${output_var} "" PARENT_SCOPE)
    return()
  endif()

  # Prefer file basename over full path to avoid false positives from directory names.
  get_filename_component(_candidate_file "${input_value}" NAME)
  string(TOLOWER "${_candidate_file}" _candidate_file_lower)
  string(TOLOWER "${input_value}" _candidate_path_lower)

  if(_candidate_file_lower MATCHES "mkl")
    set(${output_var} "MKL" PARENT_SCOPE)
    return()
  endif()
  if(_candidate_file_lower MATCHES "openblas")
    set(${output_var} "OpenBLAS" PARENT_SCOPE)
    return()
  endif()
  if(_candidate_file_lower MATCHES "flexiblas")
    set(${output_var} "FlexiBLAS" PARENT_SCOPE)
    return()
  endif()
  if(_candidate_file_lower MATCHES "blis")
    set(${output_var} "BLIS" PARENT_SCOPE)
    return()
  endif()
  if(_candidate_file_lower MATCHES "atlas")
    set(${output_var} "ATLAS" PARENT_SCOPE)
    return()
  endif()
  if(_candidate_file_lower MATCHES "goto")
    set(${output_var} "GotoBLAS" PARENT_SCOPE)
    return()
  endif()

  if(_candidate_file_lower MATCHES "accelerate|veclib")
    set(${output_var} "Accelerate" PARENT_SCOPE)
    return()
  endif()

  # Fallback for non-file tokens (e.g., BLA_VENDOR names or unusual linker tokens).
  if(_candidate_path_lower MATCHES "mkl|intel")
    set(${output_var} "MKL" PARENT_SCOPE)
  elseif(_candidate_path_lower MATCHES "openblas")
    set(${output_var} "OpenBLAS" PARENT_SCOPE)
  elseif(_candidate_path_lower MATCHES "accelerate|veclib")
    set(${output_var} "Accelerate" PARENT_SCOPE)
  elseif(_candidate_path_lower MATCHES "flexiblas")
    set(${output_var} "FlexiBLAS" PARENT_SCOPE)
  elseif(_candidate_path_lower MATCHES "blis")
    set(${output_var} "BLIS" PARENT_SCOPE)
  elseif(_candidate_path_lower MATCHES "atlas")
    set(${output_var} "ATLAS" PARENT_SCOPE)
  elseif(_candidate_path_lower MATCHES "goto")
    set(${output_var} "GotoBLAS" PARENT_SCOPE)
  else()
    set(${output_var} "" PARENT_SCOPE)
  endif()
endfunction()

function(_uni20_vendor_macro_name vendor_name output_var)
  string(TOUPPER "${vendor_name}" _vendor_upper)
  string(REGEX REPLACE "[^A-Z0-9]+" "_" _vendor_upper "${_vendor_upper}")
  string(REGEX REPLACE "_+" "_" _vendor_upper "${_vendor_upper}")
  string(REGEX REPLACE "^_" "" _vendor_upper "${_vendor_upper}")
  string(REGEX REPLACE "_$" "" _vendor_upper "${_vendor_upper}")

  if(_vendor_upper STREQUAL "")
    set(_vendor_upper "GENERIC")
  endif()

  set(${output_var} "UNI20_BLAS_VENDOR_${_vendor_upper}" PARENT_SCOPE)
endfunction()

function(_uni20_imported_blas_files target config output_var)
  # Follow CMake's imported-configuration selection order. A declared mapping
  # is exclusive; its empty entries select the configuration-less properties.
  string(TOUPPER "${config}" _config)
  get_property(_mapped TARGET ${target} PROPERTY "MAP_IMPORTED_CONFIG_${_config}" SET)
  if(_mapped)
    get_target_property(_candidates ${target} "MAP_IMPORTED_CONFIG_${_config}")
    set(_suffixes "")
    foreach(_candidate IN LISTS _candidates)
      if(_candidate STREQUAL "")
        list(APPEND _suffixes "NONE")
      else()
        string(TOUPPER "${_candidate}" _candidate)
        list(APPEND _suffixes "_${_candidate}")
      endif()
    endforeach()
    if(NOT _suffixes)
      set(_suffixes "NONE")
    endif()
  else()
    set(_suffixes "_${_config}" "NONE")
    get_target_property(_available ${target} IMPORTED_CONFIGURATIONS)
    if(_available)
      foreach(_candidate IN LISTS _available)
        string(TOUPPER "${_candidate}" _candidate)
        list(APPEND _suffixes "_${_candidate}")
      endforeach()
    endif()
  endif()

  set(_files "")
  foreach(_suffix IN LISTS _suffixes)
    if(_suffix STREQUAL "NONE")
      set(_suffix "")
    endif()
    foreach(_property IN ITEMS IMPORTED_LOCATION IMPORTED_IMPLIB)
      get_target_property(_file ${target} "${_property}${_suffix}")
      if(_file)
        list(APPEND _files "${_file}")
      endif()
    endforeach()
    if(_files)
      break()
    endif()
  endforeach()
  set(${output_var} "${_files}" PARENT_SCOPE)
endfunction()

function(detect_blas_vendor)
  unset(UNI20_REQUESTED_BLAS_VENDOR CACHE)
  unset(UNI20_DETECTED_BLAS_REQUESTED_VENDOR CACHE)

  if(NOT TARGET BLAS::BLAS AND NOT BLAS_FOUND)
    set(UNI20_DETECTED_BLAS_VENDOR "None" CACHE INTERNAL "Detected BLAS vendor" FORCE)
    _uni20_vendor_macro_name("None" _none_vendor_macro)
    set(UNI20_DETECTED_BLAS_VENDOR_MACRO "${_none_vendor_macro}" CACHE INTERNAL "Vendor-specific macro for BLAS" FORCE)
    set(UNI20_DETECTED_BLAS_LIBRARIES "" CACHE INTERNAL "Detected BLAS libraries" FORCE)
    message(STATUS "BLAS not found; UNI20_DETECTED_BLAS_VENDOR set to None")
    return()
  endif()

  # A supplied target owns its link requirements. Package variables may be
  # absent or describe an unrelated provider previously found by the parent.
  if(TARGET BLAS::BLAS)
    get_target_property(_blas_libraries BLAS::BLAS INTERFACE_LINK_LIBRARIES)
    if(NOT _blas_libraries)
      set(_blas_libraries "")
    endif()
    get_property(_multi_config GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
    if(_multi_config)
      set(_configs "${CMAKE_CONFIGURATION_TYPES}")
    elseif(CMAKE_BUILD_TYPE)
      set(_configs "${CMAKE_BUILD_TYPE}")
    else()
      set(_configs "NOCONFIG")
    endif()
    foreach(_config IN LISTS _configs)
      _uni20_imported_blas_files(BLAS::BLAS "${_config}" _blas_files)
      list(APPEND _blas_libraries ${_blas_files})
    endforeach()
    list(REMOVE_DUPLICATES _blas_libraries)
  else()
    set(_blas_libraries "${BLAS_LIBRARIES}")
  endif()

  set(_detected_vendor "")
  set(_identified_vendors "")
  foreach(_blas_lib IN LISTS _blas_libraries)
    _uni20_map_blas_vendor_name("${_blas_lib}" _mapped_vendor)
    if(NOT _mapped_vendor STREQUAL "")
      list(APPEND _identified_vendors "${_mapped_vendor}")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES _identified_vendors)
  list(LENGTH _identified_vendors _vendor_count)
  if(_vendor_count EQUAL 1)
    list(GET _identified_vendors 0 _detected_vendor)
  elseif(_vendor_count GREATER 1)
    # Vendor macros and extension availability are shared by all build configs.
    set(_detected_vendor "Generic")
  endif()

  # Opaque targets need an explicit vendor hint to enable vendor extensions.
  if(_detected_vendor STREQUAL "")
    if(DEFINED BLA_VENDOR AND NOT BLA_VENDOR STREQUAL "" AND NOT BLA_VENDOR STREQUAL "All")
      _uni20_map_blas_vendor_name("${BLA_VENDOR}" _mapped_requested_vendor)
      if(_mapped_requested_vendor STREQUAL "")
        set(_detected_vendor "${BLA_VENDOR}")
      else()
        set(_detected_vendor "${_mapped_requested_vendor}")
      endif()
    else()
      set(_detected_vendor "Generic")
    endif()
  endif()

  _uni20_vendor_macro_name("${_detected_vendor}" _vendor_macro)

  set(UNI20_DETECTED_BLAS_VENDOR "${_detected_vendor}" CACHE INTERNAL "Detected BLAS vendor" FORCE)
  set(UNI20_DETECTED_BLAS_VENDOR_MACRO "${_vendor_macro}" CACHE INTERNAL "Vendor-specific macro for BLAS" FORCE)
  set(UNI20_DETECTED_BLAS_LIBRARIES "${_blas_libraries}" CACHE INTERNAL "Detected BLAS libraries" FORCE)

  message(STATUS "Detected UNI20_DETECTED_BLAS_VENDOR: ${UNI20_DETECTED_BLAS_VENDOR}")
endfunction()
