set(_revision "unknown")
if(NOT "${REVISION_OVERRIDE}" STREQUAL "")
  set(_revision "${REVISION_OVERRIDE}")
else()
  find_package(Git QUIET)
  if(GIT_FOUND)
    # An archive nested under an unrelated checkout must not inherit that checkout's HEAD.
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" ls-files --error-unmatch -- CMakeLists.txt
      RESULT_VARIABLE _tracked OUTPUT_QUIET ERROR_QUIET)
    if(_tracked EQUAL 0)
      execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --verify HEAD
        RESULT_VARIABLE _status OUTPUT_VARIABLE _head OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
      if(_status EQUAL 0)
        set(_revision "${_head}")
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" diff --quiet HEAD -- .
          RESULT_VARIABLE _dirty OUTPUT_QUIET ERROR_QUIET)
        if(_dirty EQUAL 1)
          string(APPEND _revision "-dirty")
        elseif(NOT _dirty EQUAL 0)
          string(APPEND _revision "-unknown-status")
        endif()
      endif()
    endif()
  endif()
endif()
string(REPLACE "\\" "\\\\" _revision "${_revision}")
string(REPLACE "\"" "\\\"" _revision "${_revision}")
string(REPLACE "\n" "\\n" _revision "${_revision}")
string(REPLACE "\r" "\\r" _revision "${_revision}")
get_filename_component(_directory "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_directory}")
file(WRITE "${OUTPUT}.tmp" "#pragma once\n#include <string_view>\nnamespace ${NAMESPACE} {\ninline constexpr std::string_view source_revision = \"${_revision}\";\n}\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${OUTPUT}.tmp" "${OUTPUT}" COMMAND_ERROR_IS_FATAL ANY)
file(REMOVE "${OUTPUT}.tmp")
